@ECHO OFF
REM =========================================================================
REM BOOLTST.BAT - Testfile for module BOOL.H/C         Feb 1991 Allan Dystrup
REM               Generates default logfile: BOOL.TST
REM =========================================================================

REM default output to file (no option to bt)
set OUTFILE=bool.tst
IF %1!==!   rm %OUTFILE%

REM optional output to console (option c : override default)
IF %1!==c!  set OUTFILE=con:

echo ============================================================ >> %OUTFILE%
echo BOOL.TST (Test Logfile generated by BOOLTST.BAT)             >> %OUTFILE%
echo ============================================================ >> %OUTFILE%


echo ------------------------------------------------------------ >> %OUTFILE%
echo SCANNER - BOOLEAN OPERATORS  >> %OUTFILE%
IF %OUTFILE%==con:     pause
REM Obs: XOR operator % must be escaped as a batchfile metachar (ie: %%)
bool "ape"                     >> %OUTFILE%
bool "^ape"                    >> %OUTFILE%
bool "^^ape"                   >> %OUTFILE%
bool "ape & bee"               >> %OUTFILE%
bool "ape / bee"               >> %OUTFILE%
bool "ape %% bee"              >> %OUTFILE%
bool "^ape %% bee"             >> %OUTFILE%
bool "ape & ^bee"              >> %OUTFILE%


echo ------------------------------------------------------------ >> %OUTFILE%
echo SCANNER - PARENTHESIS     >> %OUTFILE%
IF %OUTFILE%==con:     pause
bool "ape & bee / cow"                     >> %OUTFILE%
bool "ape & (bee / cow)"                   >> %OUTFILE%
bool "ape / bee & cow %% dodo & eel"       >> %OUTFILE%
bool "((ape / bee) & (cow %% dodo)) & eel" >> %OUTFILE%


echo ------------------------------------------------------------ >> %OUTFILE%
echo SCANNER - ESCAPE          >> %OUTFILE%
IF %OUTFILE%==con:     pause
bool "ape\&&bee"               >> %OUTFILE%
bool "ape\\&bee"               >> %OUTFILE%
bool "ape\\\&bee"              >> %OUTFILE%

bool "\&ape&bee"               >> %OUTFILE%
bool "\\\&ape&bee"             >> %OUTFILE%
bool "ape&bee\\"               >> %OUTFILE%
bool "ape&bee\\\&"             >> %OUTFILE%

bool "ape&bee\"                >> %OUTFILE%

             
echo ------------------------------------------------------------ >> %OUTFILE%
echo SCANNER - QUOTE           >> %OUTFILE%
IF %OUTFILE%==con:     pause
bool ":ape&:&bee"              >> %OUTFILE%
bool "ape&:bee&:&"cow"         >> %OUTFILE%
bool "ape&:bee&:"              >> %OUTFILE%

bool "::ape&bee"               >> %OUTFILE%
bool "ape&::bee"               >> %OUTFILE%
bool "ape&bee::"               >> %OUTFILE%

bool "ape&:bee"                >> %OUTFILE%
bool ":ape & bee"              >> %OUTFILE%
bool "ape & bee:"              >> %OUTFILE%

bool "ape &\:bee\Heeve\:& cow" >> %OUTFILE%
bool "ape& :bee\\\Heeve: &cow" >> %OUTFILE%


echo ------------------------------------------------------------ >> %OUTFILE%
echo INTERPRETER               >> %OUTFILE%
IF %OUTFILE%==con:     pause
bool "a"                       >> %OUTFILE%
bool "a&b"                     >> %OUTFILE%
bool "a\b"                     >> %OUTFILE%
bool "a^b"                     >> %OUTFILE%



echo END module BOOLTST.BAT    >> %OUTFILE%    
echo ------------------------------------------------------------ >> %OUTFILE%
REM===========================================================================
